### ISSUE TITLE
printer name

### ISSUE THREAD

**Issue by petaflot** [glennerichall/OctoPrint-ZupFe#2]
in OctoPrint, my profile has a name ; yet in ZupFe it is called "unnamed printer" and I couldn't find where to set this.

help appreciated.

**Comment by glennerichall** [comment]
Its in the Appearance settings, under the property Title:

![image](https://github.com/glennerichall/OctoPrint-ZupFe/assets/2382170/fb089d8c-0229-4df1-aef3-90cfb5f78fc5)

**Comment by petaflot** [comment]
cool thanks
